### ISSUE TITLE
nn-sc-1009.yaml not regenerating 

### ISSUE THREAD

**Issue by diegochavez-io** [jarmitage/tidal-rave#1]
I'm getting this error in Supercollider on Apple silicon, M2. 

FAILURE IN SERVER /cmd failed
ERROR: NNModelInfo: can't load info file '/Library/Application Support/SuperCollider/tmp/nn-sc-1009.yaml'

**Comment by jarmitage** [comment]
Please report this here https://github.com/elgiano/nn.ar/issues
